# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: dotnet publish
      run: dotnet publish ./MemoryOverflowGenerator/MemoryOverflowGenerator.csproj -c Release --no-restore -o app  
      
    - name: Copy Dockerfile
      run: cp Dockerfile ./app
    - name: Login To Docker
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
          tags: |
            crazor6/oom-demo:latest
            crazor6/oom-demo:${{ github.run_number }}
          context: ./app
          push: true
    - name: Docker Images Lst
      run: docker images
